version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: widen

    cooldown:
      default-days: 2

    allow:
      # ensure that transitive dependencies are updated
      - dependency-type: "all"

    groups:
      # group patch updates into one PR
      patch-updates:
        update-types:
          - "patch"
        patterns:
          - "*"
      # do the same with most minor updates
      safe-minor-updates:
        update-types:
          - "minor"
        # exclude packages that could ship breaking changes or noisy deprecations in minor updates
        exclude-patterns:
          - "beautifulsoup4"
          - "curl-cffi"
          - "pandas"
