"""Defines constants used throughout the codebase."""

import re
import time

import platformdirs
import pytz

# paths to important directories
CACHE_DIR = platformdirs.user_cache_path("brlib")
CONFIG_DIR = platformdirs.user_config_path("brlib")
CACHE_DIR.mkdir(parents=True, exist_ok=True)
CONFIG_DIR.mkdir(parents=True, exist_ok=True)

# current date information
CURRENT_DATE = time.asctime()
CURRENT_YEAR = int(CURRENT_DATE[20:24])
CURRENT_MONTH = int(time.strftime("%m"))
CURRENT_DAY = int(CURRENT_DATE[8:10])

# hints for input validation
FIRST_GAMES_YEAR = 1898  # the first year from which box scores are available
FIRST_TEAMS_YEAR = 1871  # the first year from which team pages are available
FIRST_ASG_YEAR = 1933
TWO_ASG_YEARS = {1959, 1960, 1961, 1962}  # years in which two All-Star Games were held
NO_ASG_YEARS = {1945, 2020}
NO_POSTSEASON_YEARS = {
    1871,
    1872,
    1873,
    1874,
    1875,
    1876,
    1877,
    1878,
    1879,
    1880,
    1881,
    1882,
    1883,
    1891,
    1893,
    1894,
    1895,
    1896,
    1897,
    1898,
    1899,
    1900,
    1901,
    1902,
    1904,
    1994,
}

# the day after (that's when the stats are posted) the expected earliest/latest possible game dates
# these dates allow for games that are two days earlier/later than the most extreme past examples
SEASON_START_MONTH, SEASON_START_DAY = "03", "17"
SEASON_END_MONTH, SEASON_END_DAY = "11", "08"

# determine if there's been baseball played in the current year
CY_BASEBALL = (
    CURRENT_MONTH > int(SEASON_START_MONTH)
    or CURRENT_MONTH == int(SEASON_START_MONTH)
    and CURRENT_DAY >= int(SEASON_START_DAY)
)
# best safe guess at earliest plausible ASG date
CY_ASG = CURRENT_YEAR not in NO_ASG_YEARS and (
    CURRENT_MONTH > 7 or CURRENT_MONTH == 7 and CURRENT_DAY > 7
)

# selected so that hour 0 lines up with when BR should have posted the previous day's results
CACHE_TIMEZONE = pytz.timezone("US/Aleutian")

# pre-compiled regular expressions
MULTI_TEAM_REGEX = re.compile(r"\dTM")
SEASON_REGEX = re.compile(r"\d{4}")
SEASON_RANGE_REGEX = re.compile(r"\d{4}-\d{4}")
DATE_REGEX = re.compile(r"[0-1]?\d[0-3]\d")
DATE_RANGE_REGEX = re.compile(r"[0-1]?\d[0-3]\d-[0-1]?\d[0-3]\d")
GAME_ID_REGEX = re.compile(r"[A-Z0-9]{2,3}\d{9}", re.IGNORECASE)
ASG_ID_REGEX = re.compile(r"\d{4}-allstar-game(?P<doubleheader>-[12])?", re.IGNORECASE)
PLAYER_ID_REGEX = re.compile(r"[a-z.'_]{3,7}\d{2}")
TEAM_ID_REGEX = re.compile(r"[A-Z0-9]{2,3}\d{4}", re.IGNORECASE)
GAME_URL_REGEX = re.compile(
    r"https://www\.baseball-reference\.com/boxes/[A-Z0-9]{2,3}/[A-Z0-9]{2,3}\d{4}[0-1]\d[0-3]\d[0-3]\.shtml"
)
ALLSTAR_GAME_URL_REGEX = re.compile(
    r"https://www\.baseball-reference\.com/allstar/[1-2]\d{3}-allstar-game-?[1-2]?\.shtml"
)
PLAYER_URL_REGEX = re.compile(
    r"https://www\.baseball-reference\.com/players/[a-z]/[a-z.'_]{3,7}\d{2}\.shtml"
)
TEAM_URL_REGEX = re.compile(
    r"https://www\.baseball-reference\.com/teams/[A-Z0-9]{2,3}/[1-2]\d{3}\.shtml"
)
SB_ATTEMPT_REGEX = re.compile(
    r"(?P<base>2nd base|3rd base|Home) (?:off|by) (?P<pitcher>\D+)/(?P<catcher>\D+)(?P<times>\d?)"
)
PICKOFF_REGEX = re.compile(
    r"(?P<base>1st base|2nd base|3rd base|Home) by (?P<pitcher>\D+)(?P<times>\d?)"
)

# exponent used when calculating team Pythagorean W-L%
# see https://www.sports-reference.com/blog/baseball-reference-faqs/
PYTHAGOREAN_EXPONENT = 1.83

# create a dictionary of team IDs and name replacements that distinguish between teams with the same
# name and use only one name for teams that did not relocate (split seasons count as relocations)
TEAM_REPLACEMENTS: dict[str, str] = {}
for start_year, end_year, team_abv, new_name in (
    # sorted alphabetically by name, and then by start year, ascending
    (1939, 1939, "IAB", "Atlanta Black Crackers"),
    (1933, 1933, "BBS", "Baltimore Black Sox"),
    (1882, 1891, "BAL", "Baltimore Orioles (1882-1899)"),
    (1892, 1899, "BLN", "Baltimore Orioles (1882-1899)"),
    (1901, 1902, "BLA", "Baltimore Orioles (1901-1902)"),
    (1876, 1940, "BSN", "Boston Braves"),
    (1871, 1875, "BOS", "Boston Braves"),
    (1901, 1907, "BOS", "Boston Red Sox"),
    (1884, 1884, "BOS", "Boston Reds"),
    (1890, 1891, "BOS", "Boston Reds"),
    (1884, 1931, "BRO", "Brooklyn Dodgers"),
    (1879, 1885, "BUF", "Buffalo Bisons (1879-1885)"),
    (1890, 1890, "BUF", "Buffalo Bisons (1890)"),
    (1914, 1914, "BUF", "Buffalo Blues"),
    (1931, 1931, "CAG", "Chicago American Giants"),
    (1876, 1903, "CHC", "Chicago Cubs"),
    (1871, 1875, "CHI", "Chicago Cubs"),
    (1914, 1914, "CHI", "Chicago Whales"),
    (1882, 1886, "CIN", "Cincinnati Reds"),
    (1953, 1958, "CIN", "Cincinnati Reds"),
    (1876, 1879, "CIN", "Cincinnati Reds (1876-1879)"),
    (1887, 1888, "CLE", "Cleveland Spiders"),
    (1942, 1942, "CCB", "Cleveland Buckeyes"),
    (1883, 1884, "COL", "Columbus Buckeyes (1883-1884)"),
    (1921, 1921, "COB", "Columbus Buckeyes (1921)"),
    (1901, 2021, "CLE", "Cleveland Guardians"),
    (1921, 1921, "CS", "Cuban Stars West"),
    (1920, 1931, "DS", "Detroit Stars (1920-1931)"),
    (1933, 1933, "ID", "Detroit Stars (1933)"),
    (1937, 1937, "DTS", "Detroit Stars (1937)"),
    (1962, 1964, "HOU", "Houston Astros"),
    (1920, 1926, "ABC", "Indianapolis ABCs (1920-1926)"),
    (1931, 1932, "AB2", "Indianapolis ABCs (1931-1932)"),
    (1938, 1938, "AB3", "Indianapolis ABCs (1938)"),
    (1884, 1884, "IND", "Indianapolis Hoosiers (1884)"),
    (1887, 1889, "IND", "Indianapolis Hoosiers (1887-1889)"),
    (1884, 1884, "KCC", "Kansas City Cowboys (1884)"),
    (1886, 1886, "KCN", "Kansas City Cowboys (1886)"),
    (1888, 1889, "KCC", "Kansas City Cowboys (1888-1889)"),
    (1997, 2004, "ANA", "Los Angeles Angels"),
    (1965, 1996, "CAL", "Los Angeles Angels"),
    (2005, 2015, "LAA", "Los Angeles Angels"),
    (1931, 1931, "LOW", "Louisville Black Caps"),
    (1882, 1884, "LOU", "Louisville Colonels"),
    (1993, 2011, "FLA", "Miami Marlins"),
    (1884, 1884, "MIL", "Milwaukee Brewers (1884)"),
    (1891, 1891, "MIL", "Milwaukee Brewers (1891)"),
    (1901, 1901, "MLA", "Milwaukee Brewers (1901)"),
    (1883, 1884, "NYG", "New York Giants"),
    (1890, 1890, "NYI", "New York Giants (1890)"),
    (1903, 1912, "NYY", "New York Yankees"),
    (1871, 1875, "ATH", "Philadelphia Athletics (1871-1876)"),
    (1876, 1876, "ATH", "Philadelphia Athletics (1871-1876)"),
    (1882, 1890, "PHA", "Philadelphia Athletics (1882-1890)"),
    (1890, 1890, "PHQ", "Philadelphia Athletics (1890-1891)"),
    (1891, 1891, "PHA", "Philadelphia Athletics (1890-1891)"),
    (1883, 1885, "PHI", "Philadelphia Phillies"),
    (1942, 1942, "PHI", "Philadelphia Phillies"),
    (1882, 1894, "PIT", "Pittsburgh Pirates"),
    (1882, 1899, "STL", "St. Louis Cardinals"),
    (1920, 1921, "SLG", "St. Louis Stars (1920-1931)"),
    (1922, 1931, "SLS", "St. Louis Stars (1920-1931)"),
    (1937, 1937, "SL2", "St. Louis Stars (1937)"),
    (1939, 1939, "SL3", "St. Louis Stars (1939)"),
    (1879, 1879, "SYR", "Syracuse Stars (1879)"),
    (1890, 1890, "SYR", "Syracuse Stars (1890)"),
    (1998, 2007, "TBD", "Tampa Bay Rays"),
    (1872, 1872, "NAT", "Washington Nationals (1872)"),
    (1875, 1875, "WAS", "Washington Nationals (1875)"),
    (1884, 1884, "WAS", "Washington Nationals (1884, AA)"),
    (1884, 1884, "WHS", "Washington Nationals (1884, UA)"),
    (1886, 1889, "WHS", "Washington Nationals (1886-1889)"),
    (1901, 1960, "WSH", "Washington Nationals (1901-1960)"),
    (1891, 1891, "WAS", "Washington Senators (1891-1899)"),
    (1892, 1899, "WHS", "Washington Senators (1891-1899)"),
):
    for season in range(start_year, end_year + 1):
        team_id = f"{team_abv}{season}"
        TEAM_REPLACEMENTS[team_id] = new_name

# replace all names of a venue to its best-known name, or current name, if applicable
# sorted alphabetically by value and then chronologically by key, oldest-to-newest
VENUE_REPLACEMENTS = {
    "Miller Park": "American Family Field",
    "Anaheim Stadium": "Angel Stadium of Anaheim",
    "Edison Field": "Angel Stadium of Anaheim",
    "Atlanta Stadium": "Atlanta-Fulton County Stadium",
    "Philadelphia Baseball Grounds": "Baker Bowl",
    "BB&T Park": "Bowman Field",
    "Muncy Bank Ballpark": "Bowman Field",
    "Journey Bank Ballpark": "Bowman Field",
    "3Com Park": "Candlestick Park",
    "Bank One Ballpark": "Chase Field",
    "White Sox Park": "Comiskey Park I",
    "Mile High Stadium": "Coors Field",
    "Redland Field": "Crosley Field",
    "Enron Field": "Daikin Park",
    "Minute Maid Park": "Daikin Park",
    "The Ballpark in Arlington": "Globe Life Park in Arlington",
    "Ameriquest Field": "Globe Life Park in Arlington",
    "Rangers Ballpark in Arlington": "Globe Life Park in Arlington",
    "Joe Robbie Stadium": "Hard Rock Stadium",
    "Pro Player Stadium": "Hard Rock Stadium",
    "Dolphins Stadium": "Hard Rock Stadium",
    "Dolphin Stadium": "Hard Rock Stadium",
    "Land Shark Stadium": "Hard Rock Stadium",
    "Sun Life Stadium": "Hard Rock Stadium",
    "San Diego Stadium": "Jack Murphy Stadium",
    "Qualcomm Stadium": "Jack Murphy Stadium",
    "Royals Stadium": "Kauffman Stadium",
    "Dunn Field": "League Park II",
    "Marlins Park": "loanDepot park",
    "Network Associates Coliseum": "Oakland-Alameda County Coliseum",
    "McAfee Coliseum": "Oakland-Alameda County Coliseum",
    "O.co Coliseum": "Oakland-Alameda County Coliseum",
    "RingCentral Coliseum": "Oakland-Alameda County Coliseum",
    "Oakland Coliseum": "Oakland-Alameda County Coliseum",
    "Pacific Bell Park": "Oracle Park",
    "SBC Park": "Oracle Park",
    "AT&T Park": "Oracle Park",
    "Jacobs Field": "Progressive Field",
    "Comiskey Park II": "Rate Field",
    "U.S. Cellular Field": "Rate Field",
    "Guaranteed Rate Field": "Rate Field",
    "Union Park": "Recreation Park",
    "Cinergy Field": "Riverfront Stadium",
    "D.C. Stadium": "Robert F. Kennedy Stadium",
    "SkyDome": "Rogers Centre",
    "Connie Mack Stadium": "Shibe Park",
    "Safeco Field": "T-Mobile Park",
    "Navin Field": "Tiger Stadium",
    "Briggs Stadium": "Tiger Stadium",
    "SunTrust Park": "Truist Park",
    "Weeghman Park": "Wrigley Field",
    "Cubs Park": "Wrigley Field",
    "Yankee Stadium IIx": "Yankee Stadium II",
}

# all Black major league team abbreviations
BML_TEAM_ABVS = {
    "AB2",
    "AB3",
    "ABC",
    "AC",
    "AG",
    "BBB",
    "BBS",
    "BCA",
    "BE",
    "BEG",
    "BRG",
    "CAG",
    "CBB",
    "CBE",
    "CBN",
    "CBR",
    "CC",
    "CCB",
    "CCU",
    "CEG",
    "CEL",
    "CG",
    "CHT",
    "CLS",
    "COB",
    "COG",
    "COT",
    "CRS",
    "CS",
    "CSE",
    "CSW",
    "CT",
    "CTG",
    "CTS",
    "CUP",
    "DM",
    "DS",
    "DTS",
    "DW",
    "HBG",
    "HG",
    "HIL",
    "IA",
    "IAB",
    "IC",
    "ID",
    "JRC",
    "KCM",
    "LOW",
    "LRG",
    "LVB",
    "MB",
    "MGS",
    "MRM",
    "MRS",
    "NBY",
    "ND",
    "NE",
    "NEG",
    "NLG",
    "NS",
    "NWB",
    "NYC",
    "PBG",
    "PC",
    "PK",
    "PS",
    "PTG",
    "SEN",
    "SL2",
    "SL3",
    "SLG",
    "SLS",
    "SNS",
    "TC",
    "TC2",
    "TT",
    "WAP",
    "WEG",
    "WMP",
    "WP",
}

# all Black major league franchise abbreviations
BML_FRANCHISE_ABVS = {
    "AB2",
    "ABC",
    "AG",
    "BAG",
    "BBB",
    "BBS",
    "BCA",
    "BEG",
    "BR2",
    "CAG",
    "CBB",
    "CBE",
    "CBN",
    "CCU",
    "CEL",
    "CG",
    "CHT",
    "CL2",
    "COB",
    "COG",
    "COT",
    "CRS",
    "CSE",
    "CSW",
    "CT",
    "CTG",
    "CTS",
    "CUP",
    "DS",
    "DTS",
    "DW",
    "DYM",
    "HBG",
    "HG",
    "HIL",
    "IA",
    "IC",
    "JRC",
    "KCM",
    "LRG",
    "LVB",
    "MB",
    "MGS",
    "MRM",
    "MRS",
    "NBY",
    "ND",
    "NE",
    "NLG",
    "NS",
    "NWB",
    "NYC",
    "PBG",
    "PBK",
    "PC",
    "PS",
    "PTG",
    "SEN",
    "SL2",
    "SLS",
    "SNH",
    "TT",
    "WAP",
    "WP",
}

# alternate abbreviations used in box score urls
TEAM_ALIASES = {
    "BTT": "BRF",
    "CHC": "CHN",
    "CHI": "CHF",
    "CHW": "CHA",
    "CLV": "CL4",
    "FLA": "FLO",
    "KCA": "KC1",
    "KCP": "KCF",
    "KCR": "KCA",
    "LAA": "ANA",
    "LAD": "LAN",
    "LOU": "LS3",
    "NYG": "NY1",
    "NYM": "NYN",
    "NYY": "NYA",
    "PBS": "PTF",
    "SDP": "SDN",
    "SEP": "SE1",
    "SFG": "SFN",
    "SLB": "SLA",
    "SLM": "SLF",
    "STL": "SLN",
    "TBD": "TBA",
    "TBR": "TBA",
    "WHS": "WSN",
    "WSA": "WS2",
    "WSH": "WS1",
    "WSN": "WAS",
}

# seasons between a franchise's first and last in which they didn't actually play
MISSING_SEASONS_DICT = {
    1872: {"CHI"},
    1873: {"CHI"},
    1921: {"CSW", "DM"},
    1922: {"DM"},
    1923: {"DM"},
    1924: {"DM"},
    1925: {"DM"},
    1926: {"BBB", "MRS"},
    1928: {"HIL"},
    1930: {"BBS", "HG", "HIL"},
    1931: {"BBB", "BBS", "HG", "HIL", "KCM", "LVB", "MRS", "NEG"},
    1932: {"KCM"},
    1933: {"BBB", "BCA", "KCM", "MRS"},
    1934: {"BBB", "BCA", "HG", "KCM", "MRS"},
    1935: {"BBB", "BCA", "KCM", "MRS"},
    1936: {"BBB", "BCA", "CAG", "KCM", "MRS"},
    1937: {"BCA", "NYC"},
    1938: {"NYC"},
    1939: {"BBB", "JRC"},
    1940: {"JRC"},
}

# some games need their winners altered due to forfeits (https://www.retrosheet.org/forfeits.htm)
FORFEITED_GAME_WINNERS = {
    "NY1190105130": "New York Giants",
    "DET190105310": "Detroit Tigers",
    "CLE190107230": "Washington Senators",
    "PIT190508050": "Pittsburgh Pirates",
    "NYA190609032": "New York Highlanders",
    "SLN190710051": "St. Louis Cardinals",
    "NY1190910042": "New York Giants",
    "CHN191607180": "Brooklyn Robins",
    "CHA191709090": "Chicago White Sox",
    "WS1194108150": "Boston Red Sox",
    "NY1194209262": "Boston Braves",
    "WS2197109300": "New York Yankees",
    "CLE197406040": "Texas Rangers",
    "2025-allstar-game": "NL All-Stars",
}

# for distinguishing between league and team abbreviations when processing player career totals
LEAGUE_ABVS = {
    "AA",
    "AL",
    "ANL",
    "ECL",
    "EWL",
    "FL",
    "NA",
    "NAL",
    "NL",
    "NN2",
    "NNL",
    "NSL",
    "PL",
    "UA",
    "WS",
}

# the page text and corresponding columns for scraping player awards in _scrape_bling
BLING_DICT = {
    "MVP": "MVP",
    "Cy Young": "CYA",
    "Rookie of the Year": "ROY",
    "All-Star": "AS",
    "AS MVP": "ASG MVP",
    "HR Derby Champ": "HR Derby Champ",
    "World Series": "WS Wins",
    "WS MVP": "WS MVP",
    "ALCS MVP": "LCS MVP",
    "NLCS MVP": "LCS MVP",
    "Silver Slugger": "SS",
    "Gold Glove": "GG",
    "Platinum Glove": "Platinum Glove",
    "Rivera Rel": "Rivera",
    "Hoffman Rel": "Hoffman",
    "Clemente": "Clemente",
    "Batting Title": "BA Title",
    "ERA Title": "ERA Title",
    "Triple Crown": "Triple Crown",
    "ML PoY": "TSN POY",
    "Wilson Overall Def Player": "Wilson ODP",
    "Rolaids Relief": "Rolaids",
    "Mgr of the year": "Manager of the Year",
}

# used to swap the direction of relationships in player relative lists
RELATIVES_DICT = {
    "Father": "Son",
    "Son": "Father",
    "Grandfather": "Grandson",
    "Grandson": "Grandfather",
    "Uncle": "Nephew",
    "Nephew": "Uncle",
    "Father-In-Law": "Son-In-Law",
    "Son-In-Law": "Father-In-Law",
    "Greatgrandfather": "Greatgrandson",
    "Greatgrandson": "Greatgrandfather",
    "Greatuncle": "Greatnephew",
    "Greatnephew": "Greatuncle",
    "Stepfather": "Stepson",
    "Stepson": "Stepfather",
    # include relationships that don't need swapping so that all known ones are represented
    "Brother": "Brother",
    "Cousin": "Cousin",
    "Brother-In-Law": "Brother-In-Law",
}

ALL_PLAYERS_COLS = (
    "Player ID",
    "Player",
    "Career Start",
    "Career End",
    "Active",
)

RECORDS_COLS = (
    "Franchise",
    "Games",
    "Wins",
    "Losses",
    "Ties",
    "W-L%",
)

GAME_INFO_COLS = (
    "Game",
    "Game ID",
    "Away Team",
    "Away Team ID",
    "Home Team",
    "Home Team ID",
    "Away Score",
    "Home Score",
    "Winning Team",
    "Winning Team ID",
    "Losing Team",
    "Losing Team ID",
    "Date",
    "Day of Week",
    "Start Time",
    "Attendance",
    "Venue",
    "Duration",
    "Surface",
    "Innings",
    "Field Condition",
    "Temperature",
    "Wind Speed",
    "Wind Direction",
    "Weather",
    "Precipitation",
    "Game Type",
)

GAME_BATTING_COLS = (
    "Player",
    "Player ID",
    "Position",
    "AB",
    "R",
    "H",
    "RBI",
    "BB",
    "SO",
    "PA",
    "BA",
    "OBP",
    "SLG",
    "OPS",
    "Pit",
    "Str",
    "WPA",
    "aLI",
    "WPA+",
    "WPA-",
    "cWPA",
    "acLI",
    "RE24",
    "2B",
    "3B",
    "HR",
    "TB",
    "SF",
    "SH",
    "HBP",
    "GDP",
    "IBB",
    "SB",
    "CS",
    "Pick",
    "2B SB",
    "3B SB",
    "HP SB",
    "2B CS",
    "3B CS",
    "HP CS",
    "1B Pick",
    "2B Pick",
    "3B Pick",
    "2-Out RBI",
    "LOB",
    "RISP",
    "Team ID",
    "Opponent Team ID",
    "Game ID",
)

GAME_PITCHING_COLS = (
    "Player",
    "Player ID",
    "Position",
    "IP",
    "H",
    "R",
    "ER",
    "BB",
    "SO",
    "HR",
    "ERA",
    "BF",
    "Pit",
    "Str",
    "Ctct",
    "StS",
    "StL",
    "GB",
    "FB",
    "LD",
    "Unk",
    "GSc",
    "IR",
    "IS",
    "WPA",
    "aLI",
    "cWPA",
    "acLI",
    "RE24",
    "W",
    "L",
    "GS",
    "GF",
    "CG",
    "SHO",
    "SV",
    "BS",
    "Holds",
    "Balks",
    "WP",
    "HBP",
    "IBB",
    "NH",
    "PG",
    "CNH",
    "Team ID",
    "Opponent Team ID",
    "Game ID",
)

GAME_FIELDING_COLS = (
    "Player",
    "Player ID",
    "Position",
    "PO",
    "A",
    "E",
    "DP",
    "TP",
    "OFA",
    "PB",
    "SB",
    "CS",
    "Pick",
    "2B SB",
    "3B SB",
    "HP SB",
    "2B CS",
    "3B CS",
    "HP CS",
    "1B Pick",
    "2B Pick",
    "3B Pick",
    "Team ID",
    "Opponent Team ID",
    "Game ID",
)

GAME_TEAM_INFO_COLS = (
    "Team",
    "Team ID",
    "Score",
    "Record",
    "Previous Game ID",
    "Next Game ID",
    "Result",
    "Home/Away",
    "Game ID",
)

GAME_UMP_INFO_COLS = (
    "Umpire",
    "Position",
    "Game ID",
)

PLAYER_INFO_COLS = (
    "Player",
    "Player ID",
    "Batting Hand",
    "Throwing Hand",
    "Height (in.)",
    "Weight (lbs.)",
    "Birth Date",
    "Birth City",
    "Birth State/Province",
    "Birth Country",
    "Death Date",
    "Age At Death",
    "Age At Death (Days)",
    "Death City",
    "Death State/Province",
    "Death Country",
    "Draft Team",
    "Draft Team ID",
    "Draft Round",
    "Draft Pick",
    "Draft Year",
    "Draft Type",
    "High Schools",
    "Schools",
    "Debut Date",
    "Debut Game ID",
    "Debut Age",
    "Debut Age (Days)",
    "Debut Rank",
    "Last Game",
    "Last Game ID",
    "Last Game Age",
    "Last Game Age (Days)",
    "HOF Year",
    "HOF Type",
    "HOF%",
    "Exceeded Rookie Limits",
    "Full Name",
    "bWAR",
    "Years Played",
    "Teams Played For",
    "Most Teams in a Year",
)

PLAYER_BLING_COLS = (
    "Player",
    "Player ID",
    "MVP",
    "CYA",
    "ROY",
    "AS",
    "ASG MVP",
    "HR Derby Champ",
    "WS Wins",
    "WS MVP",
    "LCS MVP",
    "SS",
    "GG",
    "Platinum Glove",
    "Rivera",
    "Hoffman",
    "Clemente",
    "BA Title",
    "ERA Title",
    "Triple Crown",
    "TSN POY",
    "Wilson ODP",
    "Rolaids",
    "Manager of the Year",
)

PLAYER_BATTING_COLS = (
    "Player",
    "Player ID",
    "Season",
    "Age",
    "Team",
    "Team ID",
    "League",
    "Game Type",
    "Batting bWAR",
    "G",
    "PA",
    "AB",
    "R",
    "H",
    "2B",
    "3B",
    "HR",
    "RBI",
    "SB",
    "CS",
    "BB",
    "SO",
    "BA",
    "OBP",
    "SLG",
    "OPS",
    "OPS+",
    "rOBA",
    "Rbat+",
    "TB",
    "GIDP",
    "HBP",
    "SH",
    "SF",
    "IBB",
    "Pos",
    "Rbat",
    "Rbaser",
    "Rdp",
    "Rfield",
    "Rpos",
    "RAA",
    "WAA",
    "Rrep",
    "RAR",
    "waaWL%",
    "162WL%",
    "oWAR",
    "dWAR",
    "oRAR",
    "BAbip",
    "ISO",
    "HR%",
    "SO%",
    "BB%",
    "EV",
    "HardH%",
    "LD%",
    "GB%",
    "FB%",
    "GB/FB",
    "Pull%",
    "Cent%",
    "Oppo%",
    "WPA",
    "cWPA",
    "RE24",
    "RS%",
    "SB%",
    "XBT%",
    "AS",
    "GG",
    "SS",
    "MVP Finish",
    "CYA Finish",
    "ROY Finish",
    "LCS MVP",
    "WS MVP",
)

PLAYER_PITCHING_COLS = (
    "Player",
    "Player ID",
    "Season",
    "Age",
    "Team",
    "Team ID",
    "League",
    "Game Type",
    "Pitching bWAR",
    "W",
    "L",
    "W-L%",
    "ERA",
    "G",
    "GS",
    "GF",
    "CG",
    "SHO",
    "SV",
    "IP",
    "H",
    "R",
    "ER",
    "HR",
    "BB",
    "IBB",
    "SO",
    "HBP",
    "BK",
    "WP",
    "BF",
    "ERA+",
    "FIP",
    "WHIP",
    "H9",
    "HR9",
    "BB9",
    "SO9",
    "SO/BB",
    "RA9",
    "RA9opp",
    "RA9def",
    "RA9role",
    "RA9extras",
    "PPFp",
    "RA9avg",
    "RAA",
    "WAA",
    "gmLI",
    "WAAadj",
    "RAR",
    "waaWL%",
    "162WL%",
    "BA",
    "OBP",
    "SLG",
    "OPS",
    "BAbip",
    "HR%",
    "K%",
    "BB%",
    "EV",
    "HardH%",
    "LD%",
    "GB%",
    "FB%",
    "GB/FB",
    "WPA",
    "cWPA",
    "RE24",
    "AS",
    "GG",
    "SS",
    "MVP Finish",
    "CYA Finish",
    "ROY Finish",
    "LCS MVP",
    "WS MVP",
    "NH",
    "PG",
    "CNH",
)

PLAYER_FIELDING_COLS = (
    "Player",
    "Player ID",
    "Season",
    "Age",
    "Team",
    "Team ID",
    "League",
    "Game Type",
    "Position",
    "G",
    "GS",
    "CG",
    "Inn",
    "Ch",
    "PO",
    "A",
    "E",
    "DP",
    "Fld%",
    "lgFld%",
    "Rtot",
    "Rtot/yr",
    "Rdrs",
    "Rdrs/yr",
    "RF/9",
    "lgRF9",
    "RF/G",
    "lgRFG",
    "PB",
    "WP",
    "SB",
    "CS",
    "CS%",
    "lgCS%",
    "Pick",
    "AS",
    "GG",
    "SS",
    "MVP Finish",
    "CYA Finish",
    "ROY Finish",
    "LCS MVP",
    "WS MVP",
)

PLAYER_SALARIES_COLS = (
    "Player",
    "Player ID",
    "Year",
    "Age",
    "Team",
    "Salary",
    "Service Time",
    "Sources",
    "Notes/Other Sources",
)

TEAM_INFO_COLS = (
    "Team",
    "Season",
    "Team ID",
    "Wins",
    "Losses",
    "Ties",
    "W-L%",
    "Division Finish",
    "Division",
    "Postseason Finish",
    "Managers",
    "President",
    "General Manager",
    "Farm Director",
    "Scouting Director",
    "Venues",
    "Attendance",
    "Attendance Rank",
    "Multi-Year Batting Park Factor",
    "Multi-Year Pitching Park Factor",
    "One-Year Batting Park Factor",
    "One-Year Pitching Park Factor",
    "Pythagorean Wins",
    "Pythagorean Losses",
    "Pythagorean W-L%",
    "Runs",
    "Runs Allowed",
    "Team Gold Glove",
    "Pennant",
    "World Series",
    "Number of Players",
    "Number of Pitchers",
)

TEAM_BATTING_COLS = (
    "Player",
    "Player ID",
    "Team",
    "Season",
    "Team ID",
    "Game Type",
    "Age",
    "Position",
    "Batting bWAR",
    "G",
    "PA",
    "AB",
    "R",
    "H",
    "2B",
    "3B",
    "HR",
    "RBI",
    "SB",
    "CS",
    "BB",
    "SO",
    "BA",
    "OBP",
    "SLG",
    "OPS",
    "OPS+",
    "rOBA",
    "Rbat+",
    "TB",
    "GIDP",
    "HBP",
    "SH",
    "SF",
    "IBB",
    "Pos",
    "Rbat",
    "Rbaser",
    "Rdp",
    "Rfield",
    "Rpos",
    "RAA",
    "WAA",
    "Rrep",
    "RAR",
    "waaWL%",
    "162WL%",
    "oWAR",
    "dWAR",
    "oRAR",
    "AS",
    "GG",
    "SS",
    "MVP Finish",
    "CYA Finish",
    "ROY Finish",
    "LCS MVP",
    "WS MVP",
)

TEAM_PITCHING_COLS = (
    "Player",
    "Player ID",
    "Team",
    "Season",
    "Team ID",
    "Game Type",
    "Age",
    "Position",
    "Pitching bWAR",
    "W",
    "L",
    "W-L%",
    "ERA",
    "G",
    "GS",
    "GF",
    "CG",
    "SHO",
    "SV",
    "IP",
    "H",
    "R",
    "ER",
    "HR",
    "BB",
    "IBB",
    "SO",
    "HBP",
    "BK",
    "WP",
    "BF",
    "ERA+",
    "FIP",
    "WHIP",
    "H9",
    "HR9",
    "BB9",
    "SO9",
    "SO/BB",
    "RA9",
    "RA9opp",
    "RA9def",
    "RA9role",
    "RA9extras",
    "PPFp",
    "RA9avg",
    "RAA",
    "WAA",
    "gmLI",
    "WAAadj",
    "RAR",
    "waaWL%",
    "162WL%",
    "AS",
    "GG",
    "SS",
    "MVP Finish",
    "CYA Finish",
    "ROY Finish",
    "LCS MVP",
    "WS MVP",
    "NH",
    "PG",
    "CNH",
)

TEAM_FIELDING_COLS = (
    "Player",
    "Player ID",
    "Team",
    "Season",
    "Team ID",
    "Game Type",
    "Age",
    "G",
    "GS",
    "CG",
    "Inn",
    "Ch",
    "PO",
    "A",
    "E",
    "DP",
    "Fld%",
    "Rtot",
    "Rtot/yr",
    "Rdrs",
    "Rdrs/yr",
    "RF/9",
    "lgRF9",
    "RF/G",
    "lgRFG",
    "PB",
    "WP",
    "SB",
    "CS",
    "CS%",
    "Pick",
    "Pos",
    "AS",
    "GG",
    "SS",
    "MVP Finish",
    "CYA Finish",
    "ROY Finish",
    "LCS MVP",
    "WS MVP",
)
