#!/usr/bin/env python3

"""Defines constants used throughout the codebase."""

import re
import time

import platformdirs
import pytz

# paths to important directories
CACHE_DIR = platformdirs.user_cache_path("brlib")
CONFIG_DIR = platformdirs.user_config_path("brlib")
CACHE_DIR.mkdir(parents=True, exist_ok=True)
CONFIG_DIR.mkdir(parents=True, exist_ok=True)

CURRENT_DATE = time.asctime()
CURRENT_YEAR = int(CURRENT_DATE[20:24])
CURRENT_MONTH = int(time.strftime("%m"))
CURRENT_DAY = int(CURRENT_DATE[8:10])

FIRST_GAMES_YEAR = 1901  # the first year from which box scores are available
FIRST_TEAMS_YEAR = 1871
FIRST_ASG_YEAR = 1933
TWO_ASG_YEARS = {1959, 1960, 1961, 1962}  # years in which two All-Star Games were held
NO_ASG_YEARS = {1945, 2020}
NO_POSTSEASON_YEARS = {1901, 1902, 1904, 1994}

# the day after (that's when the stats are posted) the expected earliest/latest possible game dates
# these dates allow for games that are two days earlier/later than the most extreme past examples
SEASON_START_DATE = "03-17"
SEASON_END_DATE = "11-08"

# determine if there's been baseball played in the current year
SEASON_START_MONTH, SEASON_START_DAY = (int(s) for s in SEASON_START_DATE.split("-"))
if (
    CURRENT_MONTH < SEASON_START_MONTH
    or CURRENT_MONTH == SEASON_START_MONTH
    and CURRENT_DAY < SEASON_START_DAY
):
    CY_BASEBALL = False
else:
    CY_BASEBALL = True

# best safe guess at earliest plausible ASG date
if CURRENT_YEAR in NO_ASG_YEARS:
    CY_ASG = False
else:
    CY_ASG = CURRENT_MONTH > 7 or CURRENT_MONTH == 7 and CURRENT_DAY > 7

# selected so that hour 0 lines up with when BR should have posted the previous day's results
CACHE_TIMEZONE = pytz.timezone("US/Aleutian")

# pre-compiled regular expressions
MULTI_TEAM_REGEX = re.compile("^[1-9]TM$")
SEASON_REGEX = re.compile("^[1-2][0-9]{3}$")
SEASON_RANGE_REGEX = re.compile("^[1-2][0-9]{3}-[1-2][0-9]{3}$")
GAME_DATE_REGEX = re.compile("^[0-9]{4}[0-1][0-9][0-3][0-9]$")
DOUBLEHEADER_REGEX = re.compile("^[0-3]$")
DATE_REGEX = re.compile("^[0-1]?[0-9][0-3][0-9]$")
DATE_RANGE_REGEX = re.compile("^[0-1]?[0-9][0-3][0-9]-[0-1]?[0-9][0-3][0-9]$")
PLAYER_ID_REGEX = re.compile("^[a-z.'_]{3,7}[0-9]{2}$")
SCHEDULE_TAG_REGEX = re.compile("^all_[0-9]")
GAME_URL_REGEX = re.compile(
    r"https://www\.baseball-reference\.com/boxes/[A-Z1-2]{2,3}/[A-Z1-2]{2,3}[0-9]{4}[0-1][0-9][0-3][0-9][0-3]\.shtml"
)
ALLSTAR_GAME_URL_REGEX = re.compile(
    r"https://www\.baseball-reference\.com/allstar/[1-2][0-9]{3}-allstar-game-?[1-2]?\.shtml"
)
PLAYER_URL_REGEX = re.compile(
    r"https://www\.baseball-reference\.com/players/[a-z]/[a-z.'_]{3,7}[0-9]{2}\.shtml"
)
TEAM_URL_REGEX = re.compile(
    r"https://www\.baseball-reference\.com/teams/[A-Z1-4]{2,3}/[1-2][0-9]{3}\.shtml"
)
SB_ATTEMPT_REGEX = re.compile(
    r"^(?P<base>2nd base|3rd base|Home) (?:off|by) (?P<pitcher>\D+)/(?P<catcher>\D+)(?P<times>[0-9]?)$"
)
PICKOFF_REGEX = re.compile(
    r"^(?P<base>1st base|2nd base|3rd base|Home) by (?P<pitcher>\D+)(?P<times>[0-9]?)$"
)

# old names for teams (which have box scores) that didn't relocate
TEAM_REPLACEMENTS = {
    "Boston Americans": "Boston Red Sox",
    "Boston Beaneaters": "Boston Braves",
    "Boston Bees": "Boston Braves",
    "Boston Doves": "Boston Braves",
    "Boston Nationals": "Boston Braves",
    "Boston Rustlers": "Boston Braves",
    "Brooklyn Robins": "Brooklyn Dodgers",
    "Brooklyn Superbas": "Brooklyn Dodgers",
    "Buffalo Buffeds": "Buffalo Blues",
    "Chicago Orphans": "Chicago Cubs",
    "Cincinnati Redlegs": "Cincinnati Reds",
    "Chicago Chi-Feds": "Chicago Whales",
    "Cleveland Blues": "Cleveland Guardians",
    "Cleveland Bronchos": "Cleveland Guardians",
    "Cleveland Indians": "Cleveland Guardians",
    "Cleveland Napoleons": "Cleveland Guardians",
    "Cleveland Naps": "Cleveland Guardians",
    "Houston Colt .45s": "Houston Astros",
    "Anaheim Angels": "Los Angeles Angels",
    "California Angels": "Los Angeles Angels",
    "Los Angeles Angels of Anaheim": "Los Angeles Angels",
    "Florida Marlins": "Miami Marlins",
    "New York Highlanders": "New York Yankees",
    "Philadelphia Phils": "Philadelphia Phillies",
    "Tampa Bay Devil Rays": "Tampa Bay Rays",
}

# team's that should be renamed within the given inclusive range
RANGE_TEAM_REPLACEMENTS = (
    (1911, 1911, "Boston", "Boston Rustlers"),
    (1902, 1902, "Chicago", "Chicago Orphans"),
    (1903, 1903, "Chicago", "Chicago Cubs"),
    (1901, 1901, "Cleveland", "Cleveland Blues"),
    (1901, 1902, "Baltimore Orioles", "Baltimore Orioles (1901-1902)"),
    (1901, 1901, "Milwaukee Brewers", "Milwaukee Brewers (1901)"),
    (1901, 1956, "Washington Nationals", "Washington Nationals (1901-1960)"),
    (1901, 1960, "Washington Senators", "Washington Nationals (1901-1960)"),
)

# map all names of a venue to its best known name, or current name, if applicable
VENUE_REPLACEMENTS = {
    "Miller Park": "American Family Field",
    "Anaheim Stadium": "Angel Stadium of Anaheim",
    "Edison Field": "Angel Stadium of Anaheim",
    "BB&T Park": "Bowman Field",
    "Muncy Bank Ballpark": "Bowman Field",
    "Journey Bank Ballpark": "Bowman Field",
    "3Com Park": "Candlestick Park",
    "Bank One Ballpark": "Chase Field",
    "White Sox Park": "Comiskey Park I",
    "Mile High Stadium": "Coors Field",
    "Redland Field": "Crosley Field",
    "Enron Field": "Daikin Park",
    "Minute Maid Park": "Daikin Park",
    "The Ballpark in Arlington": "Globe Life Park in Arlington",
    "Ameriquest Field": "Globe Life Park in Arlington",
    "Rangers Ballpark in Arlington": "Globe Life Park in Arlington",
    "Comiskey Park II": "Rate Field",
    "U.S. Cellular Field": "Rate Field",
    "Guaranteed Rate Field": "Rate Field",
    "Joe Robbie Stadium": "Hard Rock Stadium",
    "Pro Player Stadium": "Hard Rock Stadium",
    "Dolphins Stadium": "Hard Rock Stadium",
    "Dolphin Stadium": "Hard Rock Stadium",
    "Land Shark Stadium": "Hard Rock Stadium",
    "Sun Life Stadium": "Hard Rock Stadium",
    "Royals Stadium": "Kauffman Stadium",
    "Marlins Park": "loanDepot park",
    "Oakland Coliseum": "Oakland-Alameda County Coliseum",
    "Network Associates Coliseum": "Oakland-Alameda County Coliseum",
    "McAfee Coliseum": "Oakland-Alameda County Coliseum",
    "O.co Coliseum": "Oakland-Alameda County Coliseum",
    "RingCentral Coliseum": "Oakland-Alameda County Coliseum",
    "Pacific Bell Park": "Oracle Park",
    "SBC Park": "Oracle Park",
    "AT&T Park": "Oracle Park",
    "Jacobs Field": "Progressive Field",
    "Cinergy Field": "Riverfront Stadium",
    "SkyDome": "Rogers Centre",
    "San Diego Stadium": "Jack Murphy Stadium",
    "Qualcomm Stadium": "Jack Murphy Stadium",
    "Connie Mack Stadium": "Shibe Park",
    "Safeco Field": "T-Mobile Park",
    "Navin Field": "Tiger Stadium",
    "Briggs Stadium": "Tiger Stadium",
    "SunTrust Park": "Truist Park",
    "Weeghman Park": "Wrigley Field",
    "Cubs Park": "Wrigley Field",
    "Yankee Stadium IIx": "Yankee Stadium II",
}

# all Black major league team abbreviations
BML_TEAM_ABVS = {
    "AB2",
    "AB3",
    "ABC",
    "AC",
    "AG",
    "BBB",
    "BBS",
    "BCA",
    "BE",
    "BEG",
    "BRG",
    "CAG",
    "CBB",
    "CBE",
    "CBN",
    "CBR",
    "CC",
    "CCB",
    "CCU",
    "CEG",
    "CEL",
    "CG",
    "CHT",
    "CLS",
    "COB",
    "COG",
    "COT",
    "CRS",
    "CS",
    "CSE",
    "CSW",
    "CT",
    "CTG",
    "CTS",
    "CUP",
    "DM",
    "DS",
    "DTS",
    "DW",
    "HBG",
    "HG",
    "HIL",
    "IA",
    "IAB",
    "IC",
    "ID",
    "JRC",
    "KCM",
    "LOW",
    "LRG",
    "LVB",
    "MB",
    "MGS",
    "MRM",
    "MRS",
    "NBY",
    "ND",
    "NE",
    "NEG",
    "NLG",
    "NS",
    "NWB",
    "NYC",
    "PBG",
    "PC",
    "PK",
    "PS",
    "PTG",
    "SEN",
    "SL2",
    "SL3",
    "SLG",
    "SLS",
    "SNS",
    "TC",
    "TC2",
    "TT",
    "WAP",
    "WEG",
    "WMP",
    "WP",
}

# all Black major league franchise abbreviations
BML_FRANCHISE_ABVS = {
    "AB2",
    "ABC",
    "AG",
    "BAG",
    "BBB",
    "BBS",
    "BCA",
    "BEG",
    "BR2",
    "CAG",
    "CBB",
    "CBE",
    "CBN",
    "CCU",
    "CEL",
    "CG",
    "CHT",
    "CL2",
    "COB",
    "COG",
    "COT",
    "CRS",
    "CSE",
    "CSW",
    "CT",
    "CTG",
    "CTS",
    "CUP",
    "DS",
    "DTS",
    "DW",
    "DYM",
    "HBG",
    "HG",
    "HIL",
    "IA",
    "IC",
    "JRC",
    "KCM",
    "LRG",
    "LVB",
    "MB",
    "MGS",
    "MRM",
    "MRS",
    "NBY",
    "ND",
    "NE",
    "NLG",
    "NS",
    "NWB",
    "NYC",
    "PBG",
    "PBK",
    "PC",
    "PS",
    "PTG",
    "SEN",
    "SL2",
    "SLS",
    "SNH",
    "TT",
    "WAP",
    "WP",
}

# alternate abbreviations used in box score urls
TEAM_ALIASES = {
    "BTT": "BRF",
    "CHC": "CHN",
    "CHI": "CHF",
    "CHW": "CHA",
    "FLA": "FLO",
    "KCA": "KC1",
    "KCP": "KCF",
    "KCR": "KCA",
    "LAA": "ANA",
    "LAD": "LAN",
    "NYG": "NY1",
    "NYM": "NYN",
    "NYY": "NYA",
    "PBS": "PTF",
    "SDP": "SDN",
    "SEP": "SE1",
    "SFG": "SFN",
    "SLB": "SLA",
    "SLM": "SLF",
    "STL": "SLN",
    "TBD": "TBA",
    "TBR": "TBA",
    "WSA": "WS2",
    "WSH": "WS1",
    "WSN": "WAS",
}

# seasons between a franchise's first and last in which they didn't actually play
MISSING_SEASONS_DICT = {
    1872: {"CHI"},
    1873: {"CHI"},
    1921: {"CSW", "DM"},
    1922: {"DM"},
    1923: {"DM"},
    1924: {"DM"},
    1925: {"DM"},
    1926: {"BBB", "MRS"},
    1928: {"HIL"},
    1930: {"BBS", "HG", "HIL"},
    1931: {"BBB", "BBS", "HG", "HIL", "KCM", "LVB", "MRS", "NEG"},
    1932: {"KCM"},
    1933: {"BBB", "BCA", "KCM", "MRS"},
    1934: {"BBB", "BCA", "HG", "KCM", "MRS"},
    1935: {"BBB", "BCA", "KCM", "MRS"},
    1936: {"BBB", "BCA", "CAG", "KCM", "MRS"},
    1937: {"BCA", "NYC"},
    1938: {"NYC"},
    1939: {"BBB", "JRC"},
    1940: {"JRC"},
}

# some games need their winners altered due to forfeits (https://www.retrosheet.org/forfeits.htm)
FORFEITED_GAME_WINNERS = {
    "NY1190105130": "New York Giants",
    "DET190105310": "Detroit Tigers",
    "CLE190107230": "Washington Senators",
    "PIT190508050": "Pittsburgh Pirates",
    "NYA190609032": "New York Highlanders",
    "SLN190710051": "St. Louis Cardinals",
    "NY1190910042": "New York Giants",
    "CHN191607180": "Brooklyn Robins",
    "CHA191709090": "Chicago White Sox",
    "WS1194108150": "Boston Red Sox",
    "NY1194209262": "Boston Braves",
    "WS2197109300": "New York Yankees",
    "CLE197406040": "Texas Rangers",
    "2025-allstar-game": "NL All-Stars",
}

# for distinguishing between league and team abbreviations when processing player career totals
LEAGUE_ABVS = {
    "AA",
    "AL",
    "ANL",
    "ECL",
    "EWL",
    "FL",
    "NA",
    "NAL",
    "NL",
    "NN2",
    "NNL",
    "NSL",
    "PL",
    "UA",
    "WS",
}

# the page text and corresponding columns for scraping player awards in _scrape_bling
BLING_DICT = {
    "MVP": "MVP",
    "Cy Young": "CYA",
    "Rookie of the Year": "ROY",
    "All-Star": "AS",
    "AS MVP": "ASG MVP",
    "HR Derby Champ": "HR Derby Champ",
    "World Series": "WS Wins",
    "WS MVP": "WS MVP",
    "ALCS MVP": "LCS MVP",
    "NLCS MVP": "LCS MVP",
    "Silver Slugger": "SS",
    "Gold Glove": "GG",
    "Platinum Glove": "Platinum Glove",
    "Rivera Rel": "Rivera",
    "Hoffman Rel": "Hoffman",
    "Clemente": "Clemente",
    "Batting Title": "BA Title",
    "ERA Title": "ERA Title",
    "Triple Crown": "Triple Crown",
    "ML PoY": "TSN POY",
    "Wilson Overall Def Player": "Wilson ODP",
    "Rolaids Relief": "Rolaids",
    "Mgr of the year": "Manager of the Year",
}

# used to swap the direction of relationships in player relative lists
RELATIVES_DICT = {
    "Father": "Son",
    "Son": "Father",
    "Grandfather": "Grandson",
    "Grandson": "Grandfather",
    "Uncle": "Nephew",
    "Nephew": "Uncle",
    "Father-In-Law": "Son-In-Law",
    "Son-In-Law": "Father-In-Law",
    "Greatgrandfather": "Greatgrandson",
    "Greatgrandson": "Greatgrandfather",
    "Greatuncle": "Greatnephew",
    "Greatnephew": "Greatuncle",
    # include relationships that don't need swapping so that unknown ones can be found
    "Brother": "Brother",
    "Cousin": "Cousin",
    "Brother-In-Law": "Brother-In-Law",
}

RECORDS_COLS = ("Franchise", "Games", "Wins", "Losses", "Ties", "W-L%")

GAME_INFO_COLS = (
    "Game",
    "Game ID",
    "Away Team",
    "Away Team ID",
    "Home Team",
    "Home Team ID",
    "Away Score",
    "Home Score",
    "Winning Team",
    "Losing Team",
    "Date",
    "Day of Week",
    "Start Time",
    "Attendance",
    "Venue",
    "Duration",
    "Surface",
    "Innings",
    "Field Condition",
    "Temperature",
    "Wind Speed",
    "Wind Direction",
    "Weather",
    "Precipitation",
    "Game Type",
)

GAME_BATTING_COLS = (
    "Player",
    "Player ID",
    "Position",
    "AB",
    "R",
    "H",
    "RBI",
    "BB",
    "SO",
    "PA",
    "BA",
    "OBP",
    "SLG",
    "OPS",
    "Pit",
    "Str",
    "WPA",
    "aLI",
    "WPA+",
    "WPA-",
    "cWPA",
    "acLI",
    "RE24",
    "2B",
    "3B",
    "HR",
    "TB",
    "SF",
    "SH",
    "HBP",
    "GDP",
    "IBB",
    "SB",
    "CS",
    "Pick",
    "2B SB",
    "3B SB",
    "HP SB",
    "2B CS",
    "3B CS",
    "HP CS",
    "1B Pick",
    "2B Pick",
    "3B Pick",
    "2-Out RBI",
    "LOB",
    "RISP",
    "Team",
    "Team ID",
    "Opponent",
    "Opponent Team ID",
    "Team Score",
    "Result for Team",
    "Home/Away",
    "Game ID",
)

GAME_PITCHING_COLS = (
    "Player",
    "Player ID",
    "Position",
    "IP",
    "H",
    "R",
    "ER",
    "BB",
    "SO",
    "HR",
    "ERA",
    "BF",
    "Pit",
    "Str",
    "Ctct",
    "StS",
    "StL",
    "GB",
    "FB",
    "LD",
    "Unk",
    "GSc",
    "IR",
    "IS",
    "WPA",
    "aLI",
    "cWPA",
    "acLI",
    "RE24",
    "W",
    "L",
    "GS",
    "GF",
    "CG",
    "SHO",
    "SV",
    "BS",
    "Holds",
    "Balks",
    "WP",
    "HBP",
    "IBB",
    "NH",
    "PG",
    "CNH",
    "Team",
    "Team ID",
    "Opponent",
    "Opponent Team ID",
    "Team Score",
    "Result for Team",
    "Home/Away",
    "Game ID",
)

GAME_FIELDING_COLS = (
    "Player",
    "Player ID",
    "Position",
    "PO",
    "A",
    "E",
    "DP",
    "TP",
    "OFA",
    "PB",
    "SB",
    "CS",
    "Pick",
    "2B SB",
    "3B SB",
    "HP SB",
    "2B CS",
    "3B CS",
    "HP CS",
    "1B Pick",
    "2B Pick",
    "3B Pick",
    "Team",
    "Team ID",
    "Opponent",
    "Opponent Team ID",
    "Team Score",
    "Result for Team",
    "Home/Away",
    "Game ID",
)

GAME_TEAM_INFO_COLS = (
    "Team",
    "Team ID",
    "Score",
    "Record",
    "Previous Game ID",
    "Next Game ID",
    "Result",
    "Home/Away",
    "Game ID",
)

PLAYER_INFO_COLS = (
    "Player",
    "Player ID",
    "Batting Hand",
    "Throwing Hand",
    "Height (in.)",
    "Weight (lbs.)",
    "Birth Date",
    "Birth City",
    "Birth State/Province",
    "Birth Country",
    "Death Date",
    "Age At Death",
    "Age At Death (Days)",
    "Death City",
    "Death State/Province",
    "Death Country",
    "Draft Team",
    "Draft Round",
    "Draft Pick",
    "Draft Year",
    "Draft Type",
    "High Schools",
    "Schools",
    "Debut Date",
    "Debut Game ID",
    "Debut Age",
    "Debut Age (Days)",
    "Debut Rank",
    "Last Game",
    "Last Game ID",
    "Last Game Age",
    "Last Game Age (Days)",
    "HOF Year",
    "HOF Type",
    "HOF%",
    "Exceeded Rookie Limits",
    "Full Name",
    "bWAR",
    "Years Played",
    "Minimum Career Earnings",
    "Teams Played For",
    "Most Teams in a Year",
)

PLAYER_BLING_COLS = (
    "Player",
    "Player ID",
    "MVP",
    "CYA",
    "ROY",
    "AS",
    "ASG MVP",
    "HR Derby Champ",
    "WS Wins",
    "WS MVP",
    "LCS MVP",
    "SS",
    "GG",
    "Platinum Glove",
    "Rivera",
    "Hoffman",
    "Clemente",
    "BA Title",
    "ERA Title",
    "Triple Crown",
    "TSN POY",
    "Wilson ODP",
    "Rolaids",
    "Manager of the Year",
)

PLAYER_BATTING_COLS = (
    "Player",
    "Player ID",
    "Season",
    "Age",
    "Team",
    "Team ID",
    "League",
    "Game Type",
    "Batting bWAR",
    "G",
    "PA",
    "AB",
    "R",
    "H",
    "2B",
    "3B",
    "HR",
    "RBI",
    "SB",
    "CS",
    "BB",
    "SO",
    "BA",
    "OBP",
    "SLG",
    "OPS",
    "OPS+",
    "rOBA",
    "Rbat+",
    "TB",
    "GIDP",
    "HBP",
    "SH",
    "SF",
    "IBB",
    "Pos",
    "Rbat",
    "Rbaser",
    "Rdp",
    "Rfield",
    "Rpos",
    "RAA",
    "WAA",
    "Rrep",
    "RAR",
    "waaWL%",
    "162WL%",
    "oWAR",
    "dWAR",
    "oRAR",
    "BAbip",
    "ISO",
    "HR%",
    "SO%",
    "BB%",
    "EV",
    "HardH%",
    "LD%",
    "GB%",
    "FB%",
    "GB/FB",
    "Pull%",
    "Cent%",
    "Oppo%",
    "WPA",
    "cWPA",
    "RE24",
    "RS%",
    "SB%",
    "XBT%",
    "Salary",
    "AS",
    "GG",
    "SS",
    "MVP Finish",
    "CYA Finish",
    "ROY Finish",
    "LCS MVP",
    "WS MVP",
)

PLAYER_PITCHING_COLS = (
    "Player",
    "Player ID",
    "Season",
    "Age",
    "Team",
    "Team ID",
    "League",
    "Game Type",
    "Pitching bWAR",
    "W",
    "L",
    "W-L%",
    "ERA",
    "G",
    "GS",
    "GF",
    "CG",
    "SHO",
    "SV",
    "IP",
    "H",
    "R",
    "ER",
    "HR",
    "BB",
    "IBB",
    "SO",
    "HBP",
    "BK",
    "WP",
    "BF",
    "ERA+",
    "FIP",
    "WHIP",
    "H9",
    "HR9",
    "BB9",
    "SO9",
    "SO/BB",
    "RA9",
    "RA9opp",
    "RA9def",
    "RA9role",
    "RA9extras",
    "PPFp",
    "RA9avg",
    "RAA",
    "WAA",
    "gmLI",
    "WAAadj",
    "RAR",
    "waaWL%",
    "162WL%",
    "BA",
    "OBP",
    "SLG",
    "OPS",
    "BAbip",
    "HR%",
    "K%",
    "BB%",
    "EV",
    "HardH%",
    "LD%",
    "GB%",
    "FB%",
    "GB/FB",
    "WPA",
    "cWPA",
    "RE24",
    "Salary",
    "AS",
    "GG",
    "SS",
    "MVP Finish",
    "CYA Finish",
    "ROY Finish",
    "LCS MVP",
    "WS MVP",
    "NH",
    "PG",
    "CNH",
)

PLAYER_FIELDING_COLS = (
    "Player",
    "Player ID",
    "Season",
    "Age",
    "Team",
    "Team ID",
    "League",
    "Game Type",
    "Position",
    "G",
    "GS",
    "CG",
    "Inn",
    "Ch",
    "PO",
    "A",
    "E",
    "DP",
    "Fld%",
    "lgFld%",
    "Rtot",
    "Rtot/yr",
    "Rdrs",
    "Rdrs/yr",
    "RF/9",
    "lgRF9",
    "RF/G",
    "lgRFG",
    "PB",
    "WP",
    "SB",
    "CS",
    "CS%",
    "lgCS%",
    "Pick",
    "Salary",
    "AS",
    "GG",
    "SS",
    "MVP Finish",
    "CYA Finish",
    "ROY Finish",
    "LCS MVP",
    "WS MVP",
)

TEAM_INFO_COLS = (
    "Team",
    "Season",
    "Team ID",
    "Wins",
    "Losses",
    "Ties",
    "Division Finish",
    "Division",
    "Postseason Finish",
    "Managers",
    "President",
    "General Manager",
    "Farm Director",
    "Scouting Director",
    "Venue",
    "Attendance",
    "Attendance Rank",
    "Multi-Year Batting Park Factor",
    "Multi-Year Pitching Park Factor",
    "One-Year Batting Park Factor",
    "One-Year Pitching Park Factor",
    "Pythagorean Wins",
    "Pythagorean Losses",
    "Runs",
    "Runs Allowed",
    "Team Gold Glove",
    "Pennant",
    "World Series",
    "Number of Players",
    "Number of Pitchers",
)

TEAM_BATTING_COLS = (
    "Player",
    "Player ID",
    "Team",
    "Season",
    "Team ID",
    "Game Type",
    "Age",
    "Position",
    "Batting bWAR",
    "G",
    "PA",
    "AB",
    "R",
    "H",
    "2B",
    "3B",
    "HR",
    "RBI",
    "SB",
    "CS",
    "BB",
    "SO",
    "BA",
    "OBP",
    "SLG",
    "OPS",
    "OPS+",
    "rOBA",
    "Rbat+",
    "TB",
    "GIDP",
    "HBP",
    "SH",
    "SF",
    "IBB",
    "Pos",
    "Rbat",
    "Rbaser",
    "Rdp",
    "Rfield",
    "Rpos",
    "RAA",
    "WAA",
    "Rrep",
    "RAR",
    "waaWL%",
    "162WL%",
    "oWAR",
    "dWAR",
    "oRAR",
    "AS",
    "GG",
    "SS",
    "MVP Finish",
    "CYA Finish",
    "ROY Finish",
    "LCS MVP",
    "WS MVP",
)

TEAM_PITCHING_COLS = (
    "Player",
    "Player ID",
    "Team",
    "Season",
    "Team ID",
    "Game Type",
    "Age",
    "Position",
    "Pitching bWAR",
    "W",
    "L",
    "W-L%",
    "ERA",
    "G",
    "GS",
    "GF",
    "CG",
    "SHO",
    "SV",
    "IP",
    "H",
    "R",
    "ER",
    "HR",
    "BB",
    "IBB",
    "SO",
    "HBP",
    "BK",
    "WP",
    "BF",
    "ERA+",
    "FIP",
    "WHIP",
    "H9",
    "HR9",
    "BB9",
    "SO9",
    "SO/BB",
    "RA9",
    "RA9opp",
    "RA9def",
    "RA9role",
    "RA9extras",
    "PPFp",
    "RA9avg",
    "RAA",
    "WAA",
    "gmLI",
    "WAAadj",
    "RAR",
    "waaWL%",
    "162WL%",
    "AS",
    "GG",
    "SS",
    "MVP Finish",
    "CYA Finish",
    "ROY Finish",
    "LCS MVP",
    "WS MVP",
    "NH",
    "PG",
    "CNH",
)

TEAM_FIELDING_COLS = (
    "Player",
    "Player ID",
    "Team",
    "Season",
    "Team ID",
    "Game Type",
    "Age",
    "G",
    "GS",
    "CG",
    "Inn",
    "Ch",
    "PO",
    "A",
    "E",
    "DP",
    "Fld%",
    "Rtot",
    "Rtot/yr",
    "Rdrs",
    "Rdrs/yr",
    "RF/9",
    "lgRF9",
    "RF/G",
    "lgRFG",
    "PB",
    "WP",
    "SB",
    "CS",
    "CS%",
    "Pick",
    "Pos",
    "AS",
    "GG",
    "SS",
    "MVP Finish",
    "CYA Finish",
    "ROY Finish",
    "LCS MVP",
    "WS MVP",
)
